name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/CI.yml"

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: On ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    env:
      DB_AUTH_TOKEN: ${{ secrets.DB_AUTH_TOKEN }}
      QDRANT_URL: ${{ vars.QDRANT_URL }}
      QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      LOG_LEVEL: DEBUG
      ENVIRONMENT: development
      DB_URL: ${{ vars.DB_URL }}
      ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          working-directory: backend

      - name: Check code
        working-directory: backend
        run: rye check
      
      - name: Upgrade database
        working-directory: backend
        run: rye run alembic upgrade head
          
      - name: Test code
        working-directory: backend
        run: rye test